apiVersion: v1
kind: Service
metadata:
  name: ncaa-api
  namespace: scenario-lab
  labels:
    app: ncaa-api
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: ncaa-api

